'use strict';
// The rendered symbol packs: what is committed has to be whole.
//
// public/slotpacks.js is generated by tools/generate-slot-symbols.js from the manifests in
// public/textures/slots/. The machine trusts it blindly — a cell it names is drawn from
// the atlas without looking — so this holds the file to its promises: every pack names a
// theme the game has, its atlas exists and is the size the cells need, and every one of
// the ten symbols has a cell inside it. A repository with no packs at all passes: the
// vector artwork is the fallback, and the file may be empty.

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { ROOT } = require('./helpers');

const KEYS = ['T', 'J', 'Q', 'K', 'A', 'BELL', 'GEM', 'CROWN', 'WILD', 'SCAT'];
const load = (rel) => import(pathToFileURL(path.join(ROOT, 'public', rel)).href);

/** The pixel size of a WebP or PNG, from its header, without decoding it. */
function imageSize(file) {
  const b = fs.readFileSync(file);
  if (b.slice(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
  }
  if (b.slice(0, 4).toString() === 'RIFF' && b.slice(8, 12).toString() === 'WEBP') {
    const chunk = b.slice(12, 16).toString();
    if (chunk === 'VP8X') return { w: 1 + b.readUIntLE(24, 3), h: 1 + b.readUIntLE(27, 3) };
    if (chunk === 'VP8L') {
      const bits = b.readUInt32LE(21);
      return { w: 1 + (bits & 0x3fff), h: 1 + ((bits >> 14) & 0x3fff) };
    }
    if (chunk === 'VP8 ') return { w: b.readUInt16LE(26) & 0x3fff, h: b.readUInt16LE(28) & 0x3fff };
  }
  throw new Error(`${path.basename(file)} is neither PNG nor WebP`);
}

test('every committed pack is whole: a known theme, an atlas that exists, a cell per symbol inside it', async () => {
  const { PACKS } = await load('slotpacks.js');
  const { THEME_KEYS } = await load('symbols.js');
  const { SLOT_THEMES } = await load('slotthemes.js');
  for (const [theme, pack] of Object.entries(PACKS)) {
    assert.ok(THEME_KEYS.includes(theme), `${theme} is not a theme the machine has`);
    assert.ok(SLOT_THEMES[theme], `${theme} has no palette`);
    assert.ok(pack.atlas.startsWith('/textures/slots/'), `${theme}: the atlas lives under /textures/slots/`);
    const file = path.join(ROOT, 'public', pack.atlas);
    assert.ok(fs.existsSync(file), `${theme}: ${pack.atlas} is missing`);
    const { w, h } = imageSize(file);
    assert.ok(Number.isInteger(pack.cell) && pack.cell >= 128, `${theme}: cell ${pack.cell}`);
    for (const key of KEYS) {
      const cell = pack.cells[key];
      assert.ok(Array.isArray(cell) && cell.length === 2, `${theme}: ${key} has no cell`);
      assert.ok(cell[0] >= 0 && cell[1] >= 0 && cell[0] + pack.cell <= w && cell[1] + pack.cell <= h,
        `${theme}: ${key} at ${cell} does not fit a ${w}x${h} atlas`);
    }
  }
});

test('the palettes cover every theme, with the fields the renderers read', async () => {
  const { THEME_KEYS } = await load('symbols.js');
  const { SLOT_THEMES, slotPalette } = await load('slotthemes.js');
  for (const theme of THEME_KEYS) {
    const p = slotPalette(theme);
    assert.ok(p, `${theme} has a palette`);
    for (const k of ['case', 'accent', 'lamp']) {
      assert.ok(Array.isArray(p[k]) && p[k].length === 3 && p[k].every((c) => c >= 0 && c <= 1.2), `${theme}.${k}`);
    }
    assert.ok(['brass', 'steel'].includes(p.bezel), `${theme}: bezel is brass or steel`);
    assert.strictEqual(p.band.length, 3, `${theme}: three band stops`);
    assert.ok(typeof p.frame === 'string' && typeof p.glow === 'string');
    assert.strictEqual(p.marquee.text.length, 3);
    assert.ok(Array.isArray(p.marquee.glow) && typeof p.marquee.small === 'string');
  }
  assert.strictEqual(slotPalette('no-such-theme'), SLOT_THEMES.classic, 'anything unknown is classic');
});
